#cloud-config
ssh_authorized_keys: (THIS KEY IS NOT VALID)
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxW8rcgzqcyOv034rdtfn3tERdBrfJNllcg3P2kQ== YOUREMAIL@HERE.COM"

runcmd:
  - sudo -i
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update -y
  - sudo apt install docker-ce docker-ce-cli containerd.io -y
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - sudo docker run --name docker-nginx -d --net host nginx

write_files:
  - path: /lib/systemd/system/nginx.service
    permission: '0644'
    content:  |
        [Unit]
        Description=The Nginx Service
        After=docker.service syslog.target network-online.target remote-fs.target nss-lookup.target 
        Wants=network-online.target
        Requires=docker.service
        
        [Service]
        Type=forking
        PIDFile=/run/nginx.pid   
        ExecStart=/usr/bin/docker run --name docker-nginx -d --net host -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf  nginx
        
        [Install]
        WantedBy=multi-user.target
